"""initial_schema

Revision ID: 18cd39afc223
Revises: 
Create Date: 2026-06-03 21:21:54.244286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cd39afc223'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_index(op.f('idx_hist_sym_int_ts'), table_name='historical_candles', if_exists=True)
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_approved')
    op.create_index(op.f('idx_hist_sym_int_ts'), 'historical_candles', ['symbol', 'interval', 'timestamp'], unique=False)
    # ### end Alembic commands ###
