"""paper_trading_and_user_scoping

Revision ID: 8adeceee7bf1
Revises: 18cd39afc223
Create Date: 2026-06-04 02:55:44.665686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adeceee7bf1'
down_revision: Union[str, Sequence[str], None] = '18cd39afc223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create backtest_results table
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('sl_price', sa.Float(), nullable=True),
    sa.Column('tp_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('r_value', sa.Float(), nullable=True),
    sa.Column('pnl_usdt', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_symbol'), 'backtest_results', ['symbol'], unique=False)

    # 2. Copy existing seeded trades into backtest_results, then clear trades
    op.execute("""
        INSERT INTO backtest_results (symbol, direction, entry_time, exit_time, entry_price,
            exit_price, sl_price, tp_price, quantity, result, r_value, pnl_usdt, commission, created_at)
        SELECT symbol, direction, entry_time, exit_time, entry_price,
            exit_price, sl_price, tp_price, quantity, result, r_value, pnl_usdt, commission, created_at
        FROM trades
    """)
    op.execute("DELETE FROM trades")

    # 3. Add user scoping columns to trades (safe now that table is empty)
    op.add_column('trades', sa.Column('user_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('trades', sa.Column('is_paper', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_foreign_key('fk_trades_user_id', 'trades', 'users', ['user_id'], ['id'])

    # 4. Add user scoping to bot_events
    op.add_column('bot_events', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('bot_events', sa.Column('is_paper', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # 5. Add user scoping to bot_state and update unique constraint
    op.add_column('bot_state', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('bot_state', sa.Column('is_paper', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_constraint('bot_state_key_key', 'bot_state', type_='unique')
    op.create_unique_constraint('uq_bot_state_scoped', 'bot_state', ['key', 'user_id', 'is_paper'])

    # 6. Create paper trading tables
    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_orders_user_id'), 'paper_orders', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_column('trades', 'is_paper')
    op.drop_column('trades', 'user_id')
    op.drop_constraint('uq_bot_state_scoped', 'bot_state', type_='unique')
    op.create_unique_constraint(op.f('bot_state_key_key'), 'bot_state', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_column('bot_state', 'is_paper')
    op.drop_column('bot_state', 'user_id')
    op.drop_column('bot_events', 'is_paper')
    op.drop_column('bot_events', 'user_id')
    op.drop_index(op.f('ix_paper_orders_user_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_table('paper_accounts')
    op.drop_index(op.f('ix_backtest_results_symbol'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
