"""add_is_rejected_to_users

Revision ID: b1267890df2e
Revises: 8adeceee7bf1
Create Date: 2026-06-04 04:36:21.257812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1267890df2e'
down_revision: Union[str, Sequence[str], None] = '8adeceee7bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_rejected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_rejected')
    # ### end Alembic commands ###
